name: travel_track
description: "开启一场不一样的旅行..."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  fl_chart: ^0.66.0
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: MuyaoSoftbrush
      fonts:
        - asset: assets/fonts/MuyaoSoftbrush.ttf
  assets:
    - assets/images/icons/
  uses-material-design: true
